// import './shili'
// import './shengmingzhouqi'
// import './data-binding'
// import './computed'
// import  './directive'
// import './conponent/define'
// import './conponent/extend'
// import './conponent/v-model'
import './conponent/features'
